spring.application.name=tasks
# H2 Database Configuration (In-Memory)
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA/Hibernate Configuration

# Auto-create/update tables on startup
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

# H2 Console (for viewing the database via a web browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console